Repository Look-Project/look, pull requests merged in 2024-04, with the labels that each got.

#5 (Feat/common-header) 공통 jsp, css 구현 및 Header 구현
  src/main/webapp/resources/css/common/common.css
  src/main/webapp/resources/css/common/header.css
  src/main/webapp/views/common/common.jsp
  src/main/webapp/views/common/header.jsp
Labels: feat

#14 Feat/vintageboard 빈티지 게시판 화면 구현
  src/main/webapp/resources/css/board/vintage/vintageboard.css
  src/main/webapp/resources/css/board/vintage/vintageboardlist.css
  src/main/webapp/resources/css/board/vintage/vintagewriteform.css
  src/main/webapp/resources/image/board/vintage/vintage1.jpg
  src/main/webapp/resources/image/board/vintage/vintage10.jpg
  src/main/webapp/resources/image/board/vintage/vintage2.jpg
  src/main/webapp/resources/image/board/vintage/vintage3.jpg
  src/main/webapp/resources/image/board/vintage/vintage4.jpg
  src/main/webapp/resources/image/board/vintage/vintage5.jpg
  src/main/webapp/resources/image/board/vintage/vintage6.jpg
  src/main/webapp/resources/image/board/vintage/vintage7.jpg
  src/main/webapp/resources/image/board/vintage/vintage8.jpg
  src/main/webapp/resources/image/board/vintage/vintage9.jpg
  src/main/webapp/resources/image/board/vintage/write_icon.jpg
  src/main/webapp/views/board/vintage/vintageboard.jsp
  src/main/webapp/views/board/vintage/vintageboardlist.jsp
  src/main/webapp/views/board/vintage/vintagewriteform.jsp
Labels: feat

#15 Feat/signup 로그인 페이지 및 회원가입 기능 구현
  src/main/java/member/controller/IdCheckController.java
  src/main/java/member/controller/LoginController.java
  src/main/java/member/controller/MemberJoinController.java
  src/main/java/member/controller/NicknameCheckController.java
  src/main/java/member/controller/SignupController.java
  src/main/java/member/dao/MemberDAO.java
  src/main/java/member/dto/request/MemberRequest.java
  src/main/java/member/dto/request/MemberSignupRequest.java
  src/main/java/member/service/MemberJoinServlce.java
  src/main/java/member/service/MemberService.java
  src/main/webapp/WEB-INF/lib/json-simple-1.1.1.jar
  src/main/webapp/resources/css/member/login.css
  src/main/webapp/resources/css/member/memberJoin.css
  src/main/webapp/resources/css/member/signup.css
  src/main/webapp/resources/js/common/common.js
  src/main/webapp/resources/js/member/memberJoin.js
  src/main/webapp/resources/js/member/memberSignup.js
  src/main/webapp/views/common/common.jsp
  src/main/webapp/views/member/login.jsp
  src/main/webapp/views/member/signup.jsp
Labels: feat

#18 Loo k mainpage JSP,CSS,JS
  src/main/webapp/resources/css/common/Mainpage.css
  src/main/webapp/resources/image/common/main0_slideshow.jpg
  src/main/webapp/resources/image/common/main1_slideshow.jpg
  src/main/webapp/resources/image/common/main2_slideshow.jpg
  src/main/webapp/resources/image/common/main3_slideshow.jpg
  src/main/webapp/resources/image/common/main4_slideshow.jpg
  src/main/webapp/resources/js/common/Mainpage_slideshow.js
  src/main/webapp/views/common/Mainpage.jsp
  src/main/webapp/views/common/header_v2.jsp
Labels: design

#26 Feat/login 로그인 기능 구현
  src/main/java/common/SessionUtil.java
  src/main/java/member/controller/LoginController.java
  src/main/java/member/dao/MemberDAO.java
  src/main/java/member/dto/request/MemberLoginRequest.java
  src/main/java/member/dto/response/MemberResponse.java
  src/main/java/member/service/MemberService.java
  src/main/webapp/resources/css/member/login.css
  src/main/webapp/resources/js/member/login.js
  src/main/webapp/views/member/login.jsp
Labels: feat

#28 Feat/page links 메인페이지 수정 및 로그인, 회원가입 리다이렉트 기능 구현
  src/main/java/common/main/controller/MainController.java
  src/main/java/member/controller/LoginController.java
  src/main/java/member/controller/SignupController.java
  src/main/webapp/resources/css/common/Mainpage.css
  src/main/webapp/resources/js/member/login.js
  src/main/webapp/views/common/Mainpage.jsp
  src/main/webapp/views/common/common.jsp
  src/main/webapp/views/common/header_v2.jsp
  src/main/webapp/views/member/login.jsp
  src/main/webapp/views/member/signup.jsp
Labels: feat

#29 Feat/logout 로그아웃 기능 구현
  src/main/java/member/controller/LogoutController.java
  src/main/webapp/resources/js/member/login.js
  src/main/webapp/views/common/header_v2.jsp
Labels: feat

#22 update: 나눔 게시판 생성
  src/main/java/board/freecycling/controller/freecyclingListCon.java
  src/main/java/board/freecycling/controller/freecyclingWriteCon.java
  src/main/java/board/freecycling/dao/freecyclingBoardDAO.java
  src/main/java/board/freecycling/dto/request/FreecyclingBoardDTO.java
  src/main/java/board/freecycling/dto/request/FreecyclingBoardIMGDTO.java
  src/main/java/board/freecycling/service/FreecyclingBoardService.java
  src/main/webapp/resources/css/board/freecyclingCss/freecyclingMainCss.css
  src/main/webapp/resources/css/board/freecyclingCss/freecyclingWriteFormCSS.css
  src/main/webapp/views/board/freecycling/freecyclingMain.jsp
  src/main/webapp/views/board/freecycling/freecyclingWriteForm.jsp
Labels: feat

#32 Feat/vintageboardlist
  src/main/java/board/vintage/controller/VintageWriteController.java
  src/main/java/board/vintage/dao/VintageDAO.java
  src/main/java/board/vintage/dto/response/VintageBoardListResponse.java
  src/main/webapp/resources/css/board/vintage/vintageboardlist.css
  src/main/webapp/views/board/vintage/vintageboardlist.jsp
  src/main/webapp/views/common/header_v2.jsp
Labels: feat, refactor

#34 빈티지 게시판 수정 및 기능 추가
  src/main/java/board/vintage/controller/VintageWriteController.java
  src/main/java/board/vintage/dao/VintageDAO.java
  src/main/java/board/vintage/dto/request/VintageWriteRequest.java
  src/main/webapp/views/board/vintage/vintageboard.jsp
  src/main/webapp/views/board/vintage/vintagewriteform.jsp
Labels: feat

#47 feat: vintage write with upload file
  src/main/java/board/vintage/controller/VintageWriteController.java
  src/main/java/board/vintage/dao/VintageDAO.java
  src/main/java/board/vintage/dto/request/VintageWriteRequest.java
  src/main/java/common/filter/LoginFilter.java
  src/main/webapp/views/board/vintage/vintageboardlist.jsp
  src/main/webapp/views/board/vintage/vintagewriteform.jsp
Labels: feat

#56 Feat/vintage comment
  src/main/java/board/vintage/controller/VintageBoardController.java
  src/main/java/board/vintage/dao/VintageDAO.java
  src/main/java/comment/vintage/controller/VintageCommentController.java
  src/main/java/comment/vintage/dao/VintageCommentDAO.java
  src/main/java/comment/vintage/dto/request/VintageCommentRequest.java
  src/main/java/comment/vintage/dto/response/VintageCommentResponse.java
  src/main/java/comment/vintage/service/VintageCommentService.java
  src/main/webapp/resources/css/board/vintage/vintageboard.css
  src/main/webapp/views/board/vintage/vintageboard.jsp
Labels: feat

#58 Feat/freepaging
  src/main/java/board/freecycling/controller/FreeEditCon.java
  src/main/java/board/freecycling/controller/FreeOneContentCon.java
  src/main/java/board/freecycling/controller/freeMainListCon.java
  src/main/java/board/freecycling/dao/freecyclingBoardDAO.java
  src/main/java/board/freecycling/dto/response/FreeOneContentDTO.java
  src/main/java/board/freecycling/service/BoardPage.java
  src/main/java/board/freecycling/service/FreecyclingBoardService.java
  src/main/java/board/freecycling/service/authMember.java
  src/main/java/common/SessionUtil.java
  src/main/webapp/views/board/freecycling/freecyclingOneContents.jsp
Labels: feat

#63 feat: Vintage 게시글 삭제 기능 구현 완료
  src/main/java/board/vintage/controller/VBoardDeleteController.java
  src/main/java/board/vintage/dao/VintageDAO.java
  src/main/java/board/vintage/dto/request/VintageDeleteRequest.java
  src/main/java/board/vintage/service/VintageBoardService.java
Labels: feat

#69 Feat/admin 관리자 기능 구현
  src/main/java/common/filter/LoginFilter.java
  src/main/java/member/controller/admin/AdminMemberController.java
  src/main/java/member/controller/admin/AdminMemberDeleteController.java
  src/main/java/member/controller/admin/AdminMemberUpdateController.java
  src/main/java/member/dao/AdminDAO.java
  src/main/java/member/dao/MemberDAO.java
  src/main/java/member/dto/request/AdminMemberUpdateRequest.java
  src/main/java/member/dto/response/AdminMemberResponse.java
  src/main/java/member/dto/response/MemberResponse.java
  src/main/java/member/service/AdminService.java
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/resources/css/member/member_manage.css
  src/main/webapp/resources/js/member/member_manage.js
  src/main/webapp/views/member/adminpage/Member_manage.jsp
  src/main/webapp/views/member/mypage/mypage_profile.jsp
  src/main/webapp/views/member/mypage/mypage_user.jsp
Labels: feat, refactor

#71 Release/vintage board list 화면 구현
  src/main/java/board/vintage/dao/VintageDAO.java
  src/main/java/board/vintage/dto/response/VintageBoardListResponse.java
  src/main/webapp/resources/css/board/vintage/vintageboardlist.css
  src/main/webapp/views/board/vintage/vintageboardlist.jsp
Labels: design

#72 페이징 디자인 변경 및 프로필 기능 수정
  src/main/java/member/controller/SignupController.java
  src/main/java/member/dao/MemberDAO.java
  src/main/java/member/dto/request/MemberSignupRequest.java
  src/main/java/member/service/AdminService.java
  src/main/webapp/resources/css/member/member_manage.css
  src/main/webapp/resources/js/member/mypage_profile.js
Labels: design, feat, refactor

#73 Feat/vintage 최종
  src/main/webapp/resources/css/board/vintage/vintageboardlist.css
  src/main/webapp/resources/css/board/vintage/vintagewriteform.css
  src/main/webapp/resources/css/board_template/temp_list.css
  src/main/webapp/views/board/vintage/editform.jsp
  src/main/webapp/views/board/vintage/vintageboard.jsp
  src/main/webapp/views/board/vintage/vintageboardlist.jsp
  src/main/webapp/views/board/vintage/vintagewriteform.jsp
Labels: design

#75 Vintage 게시글 수정 쿼리문 수정
  src/main/java/board/vintage/controller/VBoardEditController.java
  src/main/java/board/vintage/dao/VintageDAO.java
Labels: refactor

#76 refactor: Vintage 상세 게시글 내려쓰기 오류 수정
  src/main/webapp/views/board/vintage/vintageboard.jsp
  src/main/webapp/views/board/vintage/vintagewriteform.jsp
Labels: refactor

#77 Feat/freecycling jinny
  src/main/java/board/freecycling/dao/freecyclingBoardDAO.java
  src/main/webapp/views/board/freecycling/Read.jsp
Labels: refactor

#78 refactor: Vintage DAO 카테고리 추가
  src/main/java/board/vintage/dao/VintageDAO.java
Labels: refactor

#79 빈티지 게시판 페이징 및 검색 기능 구현
  src/main/java/board/vintage/controller/VintageBoardListController.java
  src/main/java/board/vintage/dao/VintageDAO.java
  src/main/java/board/vintage/service/VintageBoardService.java
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/resources/css/board/vintage/vintageboard.css
  src/main/webapp/resources/css/board/vintage/vintageboardlist.css
  src/main/webapp/views/board/vintage/vintageboard.jsp
  src/main/webapp/views/board/vintage/vintageboardlist.jsp
Labels: design, feat, refactor
